apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::992382737665:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-va1QMPR1vaMv
      username: system:node:{{EC2PrivateDNSName}}
   mapUsers: |
    - groups:
      - expense-pod-reader          
      userarn: arn:aws:iam::992382737665:user/hari
      username: hari
kind: ConfigMap
metadata:
  creationTimestamp: "2024-07-12T05:11:29Z"
  name: aws-auth
  namespace: expense
  uid: 49f62dc4-677b-4059-b75e-f36c83255eed    #dont delete this
